"use client";
import Layout from "@/components/Layout/Layout";
import Provider from "@/providers/Provider";
import "@/styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <Layout>{children}</Layout>
    </Provider>
  );
}
